config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<style>
  .form-control{
    border:1px solid #96D4D4;
    }
    
    
</style>
<body>
  <div class=" field form-group">
   
    <%= form.text_field :first_name ,class:"form-control",placeholder:"First Name"%>
  </div>
<br>
  <div class="form-group">
    
   <%= form.text_field :last_name ,class:"form-control",placeholder:"Last Name"%>
  </div>
  <br>

  <div class="form-group">
    
    <%= form.text_field :email,class:"form-control",placeholder:"Email" %>
  </div>
  <br>

  <div class="form-group">
    
    <%= form.text_field :phone,class:"form-control",placeholder:"Phone Number" %>
  </div>
<br>
  <div class="form-group">
    
    <%= form.text_field :twitter,class:"form-control",placeholder:"Twitter" %>
  </div>
  <br>


  <div >
    <%= form.submit class:"btn btn-primary" %>
  </div>
  <br>
</body>
  
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <style>
    #customers {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;


}

#customers td, #customers th {
  border: 1px solid #96D4D4;
  padding: 10px;
  width: 15%;


}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
 
  text-align: left;
  background-color: #0077ae;
  color: white;
}

  </style>

<table id="customers">
  

   <tbody>
       <tr>
         <td><%=friend.first_name %></td>
         <td><%=friend.last_name %></td>
         <td><%=friend.email %></td>
         <td><%=friend.phone %></td>
         <td><%=friend.twitter %></td>
         <td> <%= link_to "Show this friend", friend ,class:"btn btn-outline-success"%></td>
       </tr>

    </tbody>





</table>
  

</div>

app/views/friends/edit.html.erb
<style>
  header h1 {
  font-size: 30px;
  font-weight: 700;
  background-image: linear-gradient(to left, #553c9a, #4364f7);
  color: transparent;
  background-clip: text;
  -webkit-background-clip: text;
}
</style>
<br>
<header><h1>Editing friend</h1></header>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend ,class:"btn btn-outline-success"%> |
  <%= link_to "Back to friends", friends_path ,class:"btn btn-outline-success"%>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 >Friends List</h2>
<table id="customers">
<thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th></th>

    </tr>
  </thead>
</table>

<div id="friends">

  
  <% @friends.each do |friend| %>
    <%= render friend %>
  
    
  <% end %>
</div>


<%= link_to "New friend", new_friend_path,class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<style>
  header h1 {
  font-size: 30px;
  font-weight: 700;
  background-image: linear-gradient(to left, #553c9a, #4364f7);
  color: transparent;
  background-clip: text;
  -webkit-background-clip: text;
}
</style>
<br>
<header><h1>Add New friend</h1></header>

<%= render "form", friend: @friend %>
<style>

</style>
<div >
  <%= link_to "Back to friends", friends_path,class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend),class:"btn btn-outline-secondary" %> 
  <%= link_to "Back to friends", friends_path ,class:"btn btn-outline-secondary"%>
  <br>
  <br>
  <%= button_to "Destroy this friend", @friend, method: :delete ,class:"btn btn-outline-danger"%>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Friend App' ,root_path,class:"navbar-brand"%>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Friends',friends_path,class:"nav-link"%>
          
        </li>
        <li class="nav-item">
          <%= link_to 'Add Friend',new_friend_path,class:"nav-link"%>
          
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Up',new_user_registration_path,class:"nav-link"%>
          
        </li>
        <li class="nav-item">
          <%= link_to 'Log In',new_user_session_path,class:"nav-link"%>
          
        </li>
        <li class="nav-item">
          <%= link_to 'About us',home_about_path,class:"nav-link"%>
          
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out',destroy_user_session_path,data: { "turbo-method": :delete,turbo_confirm: "Are you sure to Sign out?" },class:"nav-link"%>
          
        </li>    

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body{
        background-color: #ddd;   
    }
    h1,.content{
    margin: 0px;
    padding: 0px;
    box-sizing: border-box;
    font-family: 'Times New Roman', serif;    
}
.section{
    width:100%;
    min-height: 100vh;
    
}
.container{
    width: 80%;
    display: block;
    margin: auto;
    padding-top: 100px;
    
}
.content-section{
    float:left;
    width: 55%;
    
}
.image-section{
    float: right;
    width: 40%;
   
    
}
.image-section img{
   width: 100%;
    height: auto;
    margin-top: 10px;

}
.content-section .title{
    text-transform: uppercase;
    font-size: 28px;
   

}

.content-section .content h3{
   
    color: #5d5d5d;
    margin-right: 300px;
    font-size: 19px;
}
.content-section .content p{
    margin-top: 10px;
    font-size: 18px;
    line-height: 1.5;
    text-align: justify;
    text-justify: inter-word;

    
}
.content-section .content b{
    margin-left: 2px;
    font-size: 20px;
}
.content-section .content .button {
    margin-top: 30px;
    
}
.content-section .content .button a{
    background-color: #3d3d3d;
    padding: 12px 40px;
    text-decoration: none;
    color: #fff;
    font-size: 25px;
    letter-spacing: 1.5px;
    margin-left: 10px;
}
.content-section .content .button a:hover{
    background-color: #a52a2a;
    color: #fff;
}
.content-section .social{
    margin-top: 40px;
    
}
.content-section .social i{
    color:#0082e6;
    font-size: 30px;
    padding: 0px 10px;
    
}
.content-section .social i:hover{
    color: #3d3d3d;
    
}
@media screen and (max-width:768px){
    .container{
    width: 80%;
    display: block;
    margin: auto;
    padding-top: 50px;
    
}
.content-section{
    float:none;
    width: 100%;
    display: block;
    margin: auto;
    
}
    .image-section{
    float:none;
    width: 100%;
    
    }
    .image-section img{
        width:100%;
        height: auto;
        display: block;
        margin: auto;
        
    }
    .content-section .title{
        text-align: center;
        font-size: 19px;
    }
    .content-section .content .button{
        text-align: center;
    }
    .content-section .content .button a{
     padding: 9px 30px;
    }
    .content-section .social{
        text-align: center;
    }
    .content-section .content h3{
    margin-left: 10px;
    color: #5d5d5d;
    font-weight: normal;
    
    }
    
}

</style>
</head>
<body>
<div class="section">
    <div class="container">
        <div class="content-section">
            <div class="title">
                 <h1>About Us</h1>
                 
            </div> 
            <div class="content">
                <b>Meet new people with Friends App</b>
                <p>The main theme is to Friends-App in anytime,and easily communicate with every one.Friend-App is a place for people who are looking to make new friends! By choosing from over 100 activities and interests, Friender will help you meet people nearby with the goal of creating real friendships! Text messages. To me, sending text messages seems like the easiest approach to maintaining contact with friends in the absence of social media. 

                Remove Friends On Friend App is a productivity app which help you manage your friends on Friend App.Remove Friends For Friend App allows you to find, select & remove/unfriend selected inactive friends quick & easily on Facebook with one click.Go to that profile by typing their profile name into the search bar at the top. Tap Friends. Tap Unfriend, then tap Confirm.</p>
         
                <div class="button">
                     <a href="">Read More</a>
                </div>
            </div>
    <div class="social">
         <i class="fa fa-facebook "style="font-size:24px"></i>
         
         <i class="fa fa-twitter" style="font-size:24px"></i>
         <i class="fa fa-linkedin" style="font-size:24px"></i>
         <i class="fa fa-instagram" style="font-size:24px"></i>
    </div>
    </div>
       <div class="image-section">
            <%= image_tag("logos/fd.jpg") %>
       </div>
    </div>
</div>
    

app/views/home/index.html.erb
<!Doctype html>
<head>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<style >
		*{
    padding: 0;
    margin:0;
    text-decoration: none;
    list-style: none;
    box-sizing: border-box;
    
   }
main{
    background: url(<%=asset_path 'logos/moun.jpg'%>);
    background-size: cover;
    height: calc(100vh - 80px);
}
.hero-text {
  text-align: center;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: white;
}
.hero-text h1{
    font-size: 50px;
    font-family: montserrat;
}
.hero-text h2
{

    font-family: montserrat;
}
.hero-btn{
  display: inline-block;
  text-decoration: none;
  color: #fff;
  border: 1px solid #fff;
  padding: 12px 34px;
  font-size: 13px;
  background: transparent;
  position: relative;
  cursor: pointer;
}
.hero-btn:hover{
    border: 1px solid #f44336;
    background: #f44336;
    transition: 1s;
}




.course{
    width: 80%;
    margin: auto;
    text-align: center;
    padding-top: 100px;
}
h1{
    font-size: 36px;
    font-weight: 600;
    
} 
p{
    color: #777;
    font-size: 14px;
    font-weight: 300;
    line-height: 22px;
    padding: 10px;
    font:sans-serif;

}
.row{
    margin-top: 5%;
    display: flex;
    justify-content: space-between;
}
.course-col{
    flex-basis: 31%;
    background: #fff3f3;
    border-radius: 10px;
    margin-bottom: 5%;
    padding: 20px 12px;
    box-sizing: border-box;
    transition: 0.5s;
}
.course-col p{
    text-align: justify;
    text-justify: inter-word;
    font-family: Arial,Helvetica,sans-serif;
    line-height: 1.6;
}

h3{
    text-align: center;
    font-weight: 600;
    margin: 10px 0;
}
.course-col:hover{
    box-shadow: 0 0 20px 0px rgba(0,0,0,0.2);
    
}
.footer{
    width: 100%;
    text-align: center;
    padding: 30px 0;
    
}
.icons .fa{
    color:#0082e6;
    margin: 0 13px;
    cursor: pointer;
    padding: 18px 0;
    
}
.fa-heart-o{
    color:#0082e6;
}
	</style>
	
</head>
<body>
	<main>
    <div class="hero-text">
    <a><br><br><br><br></a>
    
    <h1 ><b>Friends App</b></h1>

    <a><br></a>
    
    <h2>Make New Friends </h2>
    <a><br></a>
    
    <a href="" class="hero-btn">Visit Us To Know More</a>
  </div>
     </main>



<section class="course">
       
        <h1 >Categories </h1>
        <p>Lets make new friends</p>
        <div class="row">
          <div class="course-col">
            <h3>Add friends</h3>
            <p>The Steam app, which is available for Android and iOS, offers most of the same functionality as the desktop app. Some things are in slightly different places, but you can still accomplish most of the same tasks, including adding friends.Steam users can change their profile names at any time.The friend desktop app is virtually identical to the friend website, so you can add friends.Add friends with this add page .</p>
          </div>
          <div class="course-col" >
              <h3>Edit Friends</h3>
              <p>You’ll need to visit our desktop (non-mobile) site to edit your friends list. You can learn how to switch between mobile to desktop here. Once you're on the desktop site, click on the Friends icon at the top right (the silhouettes, next to your profile picture) and find the friend in question. Once you click edit friends link at the top of your Friends list, you can add or revoke top friend status. Edit friends with the editing form page.</p>
           </div>
           <div class="course-col">
             <h3>Unfriend</h3>
             <p>Remove Friends On Friend App is a productivity app which help you manage your friends on Friend App.Remove Friends For Friend App allows you to find, select & remove/unfriend selected inactive friends quick & easily on Friend App with one click.Go to that profile by typing their profile name into the search bar at the top. Tap Friends then Tap Unfriend, then tap Confirm.Delete friend from the friends listing page.</p>
           </p>
           </div>
          
        </div>
        </section>    

        <section class="footer">
        <h3>About Us</h3>
        <p>The main theme is to Friends-App in anytime,and easily communicate with every one.Friend-App is a place for people who are looking to make new friends! By choosing from over 100<br> activities and interests, Friender will help you meet people nearby with the goal of creating real friendships! Text messages. To me, sending text messages seems<br> like the easiest approach to maintaining contact with friends in the absence of social media </p>
       <div class="icons">
         <i class="fa fa-facebook "style="font-size:24px"></i>
         
         <i class="fa fa-twitter" style="font-size:24px"></i>
         <i class="fa fa-linkedin" style="font-size:24px"></i>
         <i class="fa fa-instagram" style="font-size:24px"></i>
        </div>
        <p>Made with <i class="fa fa-heart-o" ></i> by FriendsApp</p>
    </section>




</body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    
    <%=render 'home/header' %>
    <div clas="container">
        </div>
        <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>





<!--<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    HEADER HERE...<br/><br/>
    <%= yield %>
    <br/><br/>
    Footer Here...
  </body>
</html>

















<!--<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    HEADER HERE...<br/><br/>
    <%= yield %>
    <br/><br/>
    Footer Here...
  </body>
</html>